version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
    - 80:80
    volumes:
    - ./html:/usr/share/nginx/html
    - ./conf/nginx.conf:/etc/nginx/nginx.conf
  php:
    image: bitnami/php-fpm:8.3.6
    volumes:
    - ./html:/var/www/html
  mysql:
    image: mysql/mysql-server:8.0.23
    environment:
      MYSQL_ROOT_PASSWORD: allen
      ## 允许其他主机以root身份访问mysql
      MYSQL_ROOT_HOST: '%'
